RentalCars/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('website.home');
})->name('home');

Route::get('/login','Frontend\LoginController@login');
Route::post('/login','Frontend\LoginController@postLogin')->name('login');

Route::get('/register','Frontend\RegistrationController@register');
Route::post('/register','Frontend\RegistrationController@postRegister')->name('register');

Route::get('/admin','Backend\LoginController@login');
Route::post('/admin','Backend\LoginController@postLogin')->name('admin.login');

Route::get('news','Frontend\NewsController@index')->name('news');

Route::group(['as'=>'admin.','prefix'=>'admin','namespace'=>'Backend','middleware'=>'admin'], function(){
    Route::get('/logout','LoginController@logout')->name('logout');
    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::get('profile','ProfileController@index')->name('profile');
    Route::put('profile-update','ProfileController@updateProfile')->name('profile.update');
    Route::put('password-update','ProfileController@updatePassword')->name('password.update');
    Route::resource('manufacter','ManufacterController');
    Route::resource('seat','SeatController');
    Route::resource('car','CarController');
    Route::resource('post','PostController');
    Route::resource('contact','ContactController');
    Route::get('logo-slide','BannerController@showLogoAndSlide')->name('banner');
    Route::post('logo','BannerController@updateLogo')->name('banner.updateLogo');
    Route::post('slide','BannerController@updateSlide')->name('banner.updateSlide');
    //     Route::get('/author/index','AuthorController@index')->name('author.index');
    //     Route::get('/pending/post','PostController@pending')->name('post.pending');
    //     Route::put('/post/approveAll','PostController@approvalAll')->name('post.approveAll');
    //     Route::put('/post/{id}/approve','PostController@approval')->name('post.approve');
});

RentalCars/app/Models/Seat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Seat extends Model
{
    protected $table = "seats";

    protected $fillable = [
        'number_of_seats',
    ];

    public function cars() {
        return $this->hasMany('App\Models\Car');
    }
}

RentalCars/app/Http/Controllers/Backend/SeatController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Seat;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Brian2694\Toastr\Facades\Toastr;

class SeatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $seats = Seat::all();
        return view('admin.seat.index',compact('seats'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.seat.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'number_of_seats' => 'required|unique:seats',
        ]);

        $seat = new Seat();
        $seat->number_of_seats = $request->number_of_seats;
        $seat->save();
        Toastr::success('Number Of Seats Successfully Created' ,'Success');
        return redirect()->route('admin.seat.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $seat = Seat::find($id);
        return view('admin.seat.edit',compact('seat'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'number_of_seats' => 'required|unique:seats'
        ]);
        $seat = Seat::find($id);
        $seat->number_of_seats = $request->number_of_seats;
        $seat->save();
        Toastr::success('Number Of Seats Successfully Updated','Success');
        return redirect()->route('admin.seat.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $seat = Seat::find($id);
        $seat->delete();
        return redirect()->back();
    }
}

RentalCars/resources/views/admin/seat/create.blade.php
@extends('layouts.backend.common')
@section('title','Add Number Of Seats')
@section('content')
<!-- Start content -->
<div class="content">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="page-title-box">
					<h4 class="page-title">Add Number Of Seats</h4>
					<ol class="breadcrumb p-0 m-0">
						<li>
							<a href="{{route('admin.dashboard')}}">
								Reantal Cars
							</a>
						</li>
						<li>Management</li>
						<li>Number Of Seats</li>
					</ol>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
		<!-- end row -->

		<div class="row">
			<div class="col-xs-12">
				<div class="card-box">

					<div class="row">
						<div class="col-md-8 col-md-offset-2">

							<div class="p-20">
								<form action="{{route('admin.seat.store')}}"
									role="form" method="post">
									@csrf
									<div class="form-group">
										<label>
    										Number Of Seats
    										<span class="text-danger">*</span>
										</label>
										<input type="number"
											name="number_of_seats"
											placeholder="Enter number of seats"
											class="form-control"
											id="seatsNumber">
									</div>

									<div class="form-group text-right m-b-0">
										<button class="btn btn-success 
										waves-effect waves-light" type="submit">
										Submit</button>
										<a type="button" 
										href="{{route('admin.seat.index')}}"
										class="btn btn-default waves-effect 
										m-l-5">Cancel</a>
									</div>

								</form>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

RentalCars/resources/views/admin/seat/edit.blade.php
@extends('layouts.backend.common')
@section('title','Edit Number Of Seats')
@section('content')
<!-- Start content -->
<div class="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="page-title-box">
                    <h4 class="page-title">Edit Number Of Seats</h4>
                    <ol class="breadcrumb p-0 m-0">
                        <li>
                        	<a href="{{route('admin.dashboard')}}">
                        		Reantal Cars
                        	</a>
                        </li>
                        <li>Management</li>
                        <li>Number Of Seats</li>
                    </ol>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <!-- end row -->

        <div class="row">
            <div class="col-xs-12">
                <div class="card-box">

                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">

                            <div class="p-20">
                                <form action="{{route(
                                'admin.seat.update', $seat->id)}}"
                                      role="form" method="post">
                                    @csrf
                                    @method('PUT')
                                    <div class="form-group">
                                        <label>
                                            Number Of Seats
                                            <span class="text-danger">*</span>
                                        </label>
                                        <input type="number"
                                        	   name="number_of_seats"
                                               value="{{$seat->number_of_seats}}"
                                               class="form-control"
                                               id="seatsNumber">
                                    </div>

                                    <div class="form-group text-right m-b-0">
                                        <button class="btn btn-success
									waves-effect waves-light" type="submit">
                                            Submit</button>
                                        <a type="button"
                                           href="{{route('admin.seat.index')}}"
                                           class="btn btn-default waves-effect
									m-l-5">Cancel</a>
                                    </div>

                                </form>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

RentalCars/resources/views/admin/seat/index.blade.php
@extends('layouts.backend.common')
@section('title','Management Number Of Seats') @section('content')
<!-- Start content -->
<div class="content">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="page-title-box">
					<h4 class="page-title">Management Number Of Seats</h4>
					<ol class="breadcrumb p-0 m-0">
						<li>
							<a href="{{route('admin.dashboard')}}">
								Renatal Cars
							</a>
						</li>
						<li>Management</li>
						<li>Number Of Seats</li>
					</ol>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
		<!-- end row -->

		<div class="row">
			<div class="col-sm-12">
				<div class="card-box">
					<div class="row">
						<div class="col-md-8 col-md-offset-2">
    						<div class="demo-box m-t-20">
    							<a href="{{route('admin.seat.create')}}"
    							class="btn btn-sm  btn-success">
    								+ Add Number Of Seats
    							</a>
    							<hr />
    							<div class="table-responsive">
    								<table 
    								class="table m-0 table-colored 
    								table-custom">
    									<thead>
    										<tr>
    											<th style="width: 50px">ID</th>
    											<th style="width: 250px">
    												Number Of Seats
    											</th>
    											<th style="width: 200px">
    												Created time
    											</th>
    											<th>Action</th>
    										</tr>
    									</thead>
    									<tbody>
    										@foreach($seats as $seat)
    										<tr>
    											<td>{{$seat->id}}</td>
    											<td>
    												{{$seat->number_of_seats}}
    												seats
    											</td>
    											<td>
    												{{$seat->created_at}}
    											</td>
    											<td>
    												<a href="{{route(
    												'admin.seat.edit'
    												,$seat->id)}}" 
    												type="button" class="btn 
    												btn-sm btn-warning">
    													<i 
    													class="fa fa-pencil">
    													</i>&nbsp;Edit
    												</a>
    												&nbsp;
    												<button type="button"
    												class="btn btn-sm 
    												btn-danger"
    												onclick="deleteSeat(
        												{{$seat->id}}
    												)">
    													<i class="fa fa-trash">
    													</i>&nbsp;Delete
    												</button>
    												<form id="delete-form-{{
    													  $seat->id}}"
        												action="{{route(
        												'admin.seat.destroy'
        												,$seat->id)}}"
    													method="post"
    													style="display: none;">
                										@csrf
                										@method('DELETE')
													</form>
    											</td>
    										</tr>
    										@endforeach
    									</tbody>
    								</table>
    							</div>
    						</div>
    					</div>
					</div>
				</div>
			</div>
		</div>
	</div>
    <!-- container -->
</div>
<!-- content -->
@endsection
@push('js')
<script type="text/javascript">
	function deleteSeat(id) {
		swal({
			title: "Are you sure?",
			text: 
			"Once deleted, you will not be able to recover this number of seats!",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
			.then((willDelete) => {
			  if (willDelete) {
				event.preventDefault();
				document.getElementById('delete-form-'+id).submit();
			    swal("Success! Your number of seats has been deleted!", {
			      icon: "success",
			    });
			  } else {
			    swal("Your number of seats is safe!");
			  }
		});
	}
</script>
@endpush