RentalCars/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('website.home');
})->name('home');

Route::get('/login','Frontend\LoginController@login');
Route::post('/login','Frontend\LoginController@postLogin')->name('login');

Route::get('/register','Frontend\RegistrationController@register');
Route::post('/register','Frontend\RegistrationController@postRegister')->name('register');

Route::get('/admin','Backend\LoginController@login');
Route::post('/admin','Backend\LoginController@postLogin')->name('admin.login');

Route::get('news','Frontend\NewsController@index')->name('news');

Route::group(['as'=>'admin.','prefix'=>'admin','namespace'=>'Backend','middleware'=>'admin'], function(){
    Route::get('/logout','LoginController@logout')->name('logout');
    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::get('profile','ProfileController@index')->name('profile');
    Route::put('profile-update','ProfileController@updateProfile')->name('profile.update');
    Route::put('password-update','ProfileController@updatePassword')->name('password.update');
    Route::resource('manufacter','ManufacterController');
    Route::resource('seat','SeatController');
    Route::resource('car','CarController');
    Route::resource('post','PostController');
    Route::resource('contact','ContactController');
    Route::get('logo-slide','BannerController@showLogoAndSlide')->name('banner');
    Route::post('logo','BannerController@updateLogo')->name('banner.updateLogo');
    Route::post('slide','BannerController@updateSlide')->name('banner.updateSlide');
    //     Route::get('/author/index','AuthorController@index')->name('author.index');
    //     Route::get('/pending/post','PostController@pending')->name('post.pending');
    //     Route::put('/post/approveAll','PostController@approvalAll')->name('post.approveAll');
    //     Route::put('/post/{id}/approve','PostController@approval')->name('post.approve');
});

RentalCars/app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $table = 'contacts';
}

RentalCars/app/Http/Controllers/Backend/ContactController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.contact.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

RentalCars/resources/views/admin/contact/index.blade.php
@extends('layouts.backend.common')
@push('css')
<!-- DataTables -->
<link href="{{asset('assets/backend/plugins/datatables/jquery.dataTables.min.css')}}" rel="stylesheet" type="text/css"/>
<link href="{{asset('assets/backend/plugins/datatables/buttons.bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
<link href="{{asset('assets/backend/plugins/datatables/fixedHeader.bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
<link href="{{asset('assets/backend/plugins/datatables/responsive.bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
<link href="{{asset('assets/backend/plugins/datatables/scroller.bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
<link href="{{asset('assets/backend/plugins/datatables/dataTables.colVis.css')}}" rel="stylesheet" type="text/css"/>
<link href="{{asset('assets/backend/plugins/datatables/dataTables.bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
<link href="{{asset('assets/backend/plugins/datatables/fixedColumns.dataTables.min.css')}}" rel="stylesheet" type="text/css"/>
@endpush
@section('title','Management Posts')
@section('content')
<!-- Start content -->
<div class="content">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="page-title-box">
					<h4 class="page-title">Management Posts</h4>
					<ol class="breadcrumb p-0 m-0">
						<li><a href="{{route('admin.dashboard')}}">Renatal Cars</a></li>
						<li>Category & Product</li>
						<li>Posts</li>
					</ol>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
		<!-- end row -->

		<div class="row">
			<div class="col-sm-12">
				<div class="card-box table-responsive">
					<a  href="{{route('admin.car.create')}}"
						class="btn btn-sm  btn-success"> + Add Post </a>
					<hr />

					<table id="datatable-buttons"
						class="table table-striped table-bordered">
						<thead>
							<tr>
								<th>ID</th>
								<th>Name</th>
								<th>Image</th>
								<th>Manufacter</th>
								<th>Price</th>
								<th>Action</th>
							</tr>
						</thead>


						<tbody>
							
							
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<!-- container -->
</div>
<!-- content -->
@endsection
@push('js')
<script src="{{asset('assets/backend/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/backend/plugins/datatables/dataTables.bootstrap.js')}}"></script>

<script src="{{asset('assets/backend/plugins/datatables/dataTables.buttons.min.js')}}"></script>
<script src="{{asset('assets/backend/plugins/datatables/buttons.bootstrap.min.js')}}"></script>
<script src="{{asset('assets/backend/plugins/datatables/jszip.min.js')}}"></script>
<script src="{{asset('assets/backend/plugins/datatables/pdfmake.min.js')}}"></script>
<script src="{{asset('assets/backend/plugins/datatables/vfs_fonts.js')}}"></script>
<script src="{{asset('assets/backend/plugins/datatables/buttons.html5.min.js')}}"></script>
<script src="{{asset('assets/backend/plugins/datatables/buttons.print.min.js')}}"></script>
<script src="{{asset('assets/backend/plugins/datatables/dataTables.fixedHeader.min.js')}}"></script>
<script src="{{asset('assets/backend/plugins/datatables/dataTables.keyTable.min.js')}}"></script>
<script src="{{asset('assets/backend/plugins/datatables/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('assets/backend/plugins/datatables/responsive.bootstrap.min.js')}}"></script>
<script src="{{asset('assets/backend/plugins/datatables/dataTables.scroller.min.js')}}"></script>
<script src="{{asset('assets/backend/plugins/datatables/dataTables.colVis.js')}}"></script>
<script src="{{asset('assets/backend/plugins/datatables/dataTables.fixedColumns.min.js')}}"></script>

<!-- init -->
<script src="{{asset('assets/pages/jquery.datatables.init.js')}}"></script>

<script type="text/javascript">
	function deleteCar(id) {
		swal({
			  title: "Are you sure?",
			  text: "Once deleted, you will not be able to recover this car!",
			  icon: "warning",
			  buttons: true,
			  dangerMode: true,
			})
			.then((willDelete) => {
			  if (willDelete) {
				event.preventDefault();
				document.getElementById('delete-form-'+id).submit();
			    swal("Success! Your car has been deleted!", {
			      icon: "success",
			    });
			  } else {
			    swal("Your car is safe!");
			  }
		});
	}
</script>
@endpush